# permissions for end users to view eventwatches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eventwatch-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: event-watch
    app.kubernetes.io/part-of: event-watch
    app.kubernetes.io/managed-by: kustomize
  name: eventwatch-viewer-role
rules:
- apiGroups:
  - event.crd.liuqhahah.com
  resources:
  - eventwatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - event.crd.liuqhahah.com
  resources:
  - eventwatches/status
  verbs:
  - get
